// THIS FILE IS GENERATED - DO NOT MODIFY
/**
 *  Autogenerated by current cli tool
 */
export const BUILD_FRAMEWORK_CLI_NAME = 'tnp';
/**
 *  This value can be change in taon.jsonc (appId)
 */
export const APP_ID = 'com.domain.example.darekf77.application-quiz';
/**
 *  Autogenerated by current cli tool
 */
export const BUILD_BASE_HREF = '';
/**
 *  This value can be change in taon.jsonc (overrideNpmName)
 */
export const PROJECT_NPM_NAME = '@darekf77/application-quiz';
/**
 * Taon version from you project taon.json
 */
export const CURRENT_PACKAGE_TAON_VERSION = 'v21';
/**
 *  Autogenerated by current cli tool. Use *tnp release* to bump version.
 */
export const CURRENT_PACKAGE_VERSION = '0.0.21';

export namespace TAON_CLOUDFLARE_WORKERS_URLS {
	export const KvWorkerApplicationQuizCustom08263 = 'https://kv-worker-application-quiz-custom-08263.darekf77.workers.dev';
}

// THIS FILE IS GENERATED - DO NOT MODIFY
      