// import 'reflect-metadata';
import { createWorkerAdapter } from 'taon/lib-esm';
import { app } from '@darekf77/application-quiz/lib-esm/app.cloudflare';

export default {
  fetch: createWorkerAdapter(app),
};
// // THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
// export default {
//   fetch(): Response {
//     return new Response('OK');
//   },
// };
